_target_: sat_pred.training_module.TrainingModule
model:
  _target_: sat_pred.models.simvp_model.SimVP
  num_channels: 11
  history_len: 12
  forecast_len: 12
  checkpoint_dir: /bask/projects/v/vjgo8416-climate/users/gmmg6904/adding-time/sat_pred/checkpoint
  val_best: False
#  from_pretrained : True
optimizer:
  _target_: sat_pred.optimizers.AdamWReduceLROnPlateauGroups
  lr: 0.00005
  param_groups:
      - params_pattern: ["time"]  # adjust patterns as needed
        lr_multiplier: 10  # this group will use lr * 10
target_loss: MAE
