# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: model_config.yaml
  - datamodule: default.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - hydra: default.yaml

# Name of the model run used on wandb
model_name: "time_features_fine_tune"

seed: 27267831
