_target_: cloudcasting.dataset.SatelliteDataModule
zarr_path: 
  - /mnt/disks/sat_data/sat_data_all/2008_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2009_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2010_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2011_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2012_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2013_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2014_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2015_training_nonhrv.zarr
  - /mnt/disks/sat_data/sat_data_all/2016_training_nonhrv.zarr
history_mins: 165
forecast_mins: 180
sample_freq_mins: 15
train_period: ["2008-01-01 00:00", "2015-12-31 23:55"] # [start, end]
val_period: ["2016-01-01 00:00", "2016-12-31 23:55"]   # [start, end]
num_workers: 8
prefetch_factor: 4
batch_size: 16
nan_to_num: true
pin_memory: true
persistent_workers: true